services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/swift_codes_db
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: on-failure

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=swift_codes_db
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge